# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestUploadImageToAWSS3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestUploadImageToAWSS3
pod ‘AWSS3’

end
