# Uncomment the next line to define a global platform for your project
platform :ios, '10.6'

target 'HanDdamUserAlamofireTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HanDdamUserAlamofireTest
pod 'Alamofire', '~> 5.2'
end
